name: AI Blogger Bot

on:
  schedule:
    - cron: "0 3 * * *"   # Morning (8:30 AM IST)
    - cron: "0 7 * * *"   # Afternoon (12:30 PM IST)
    - cron: "0 11 * * *"  # Evening (4:30 PM IST)
    - cron: "0 15 * * *"  # Night (8:30 PM IST)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Bot
        run: python main.py
        env:
          NVIDIA_API_KEY: ${{ secrets.NVIDIA_API_KEY }}
          GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
          UNSPLASH_KEY: ${{ secrets.UNSPLASH_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
