name: AI Blog Bot

on:
  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Requirements
      run: |
        pip install -r requirements.txt

    - name: Create credentials.json
      run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json

    - name: Create token.json
      run: echo '${{ secrets.GOOGLE_TOKEN }}' > token.json

    - name: Run Bot
      env:
        NVIDIA_API_KEY: ${{ secrets.NVIDIA_API_KEY }}
      run: |
        python main.py
